# [\#6165 Issue](https://github.com/ethereum/solidity/issues/6165) `closed`: yulInterpreter: datacopy call fails the assertion m_functions.count(_funCall.functionName.name) in ExpressionEvaluator
**Labels**: `bug :bug:`, `fuzz-blocker`


#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) opened issue at [2019-03-04 14:15](https://github.com/ethereum/solidity/issues/6165):

## Description

(depends on #6180 )

The following code snippet

```
{datacopy(8,1,8)}
```

fails this assertion

https://github.com/ethereum/solidity/blob/6b12726f51c25840b3ccb231018fc37e994869e7/test/tools/yulInterpreter/Interpreter.cpp#L191

## Environment

- Compiler version: develop commit `21e7cadad`
- Target EVM version (as per compiler settings): constantinople
- Framework/IDE (e.g. Truffle or Remix): n/a
- EVM execution environment / backend / blockchain client: n/a
- Operating system: n/a

## Steps to Reproduce

```
$ ./test/tools/yulrun --input-file <file.yul>
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<langutil::InternalCompilerError>'
  what():  
Aborted (core dumped)
```

#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) commented at [2019-03-04 14:15](https://github.com/ethereum/solidity/issues/6165#issuecomment-469286662):

This is due to object access builtins in the yul interpreter are unimplemented. Temporary solution is to selectively discard test cases containing these builtins.

#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) commented at [2019-03-04 14:15](https://github.com/ethereum/solidity/issues/6165#issuecomment-478918291):

This is marked for today's release, any ideas how to proceed? Is this a matter of simply avoiding the assertion for certain builtins that are unsupported in the yulInterpreter or adding support for them?

#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) commented at [2019-03-04 14:15](https://github.com/ethereum/solidity/issues/6165#issuecomment-481999679):

Another scenario that fails the assertion in the title but unrelated to object access functions is the following

```
{
  for{foo() function foo() {}} 0 {}
  {
  }
}
```

My guess is that, while the `for` loop is being interpreted, the interpreter begins to interpret the function call in the init block that is not yet registered.

#### <img src="https://avatars.githubusercontent.com/u/9073706?v=4" width="50">[chriseth](https://github.com/chriseth) commented at [2019-03-04 14:15](https://github.com/ethereum/solidity/issues/6165#issuecomment-483638343):

Oh wow! That is a weird edge case! Can you open a new issue for it? I wonder whether we should disallow function declarations in for init and post blocks....

#### <img src="https://avatars.githubusercontent.com/u/2388185?v=4" width="50">[bshastry](https://github.com/bshastry) commented at [2019-03-04 14:15](https://github.com/ethereum/solidity/issues/6165#issuecomment-483647613):

@chriseth opened a new issue for the for loop init test case (#6532 )


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
