# [\#4711 Issue](https://github.com/ethereum/solidity/issues/4711) `closed`: Crash when calling a non callable type on a non primitive type double assignment
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/388605?u=c038834687e1b11f1cfc815c338b03a3938a235b&v=4" width="50">[mattaereal](https://github.com/mattaereal) opened issue at [2018-08-06 21:05](https://github.com/ethereum/solidity/issues/4711):

_This issue is being reported as part of the current audit being held by Zeppelin Solutions to Solidity's compiler (tag v0.4.24)._

## Description
Compiler crashes when a non callable type (`int`, `uint`, `struct`, etc) is used outside a double assignment involving structs.

## Error in file
Empty message.
`libsolidity/analysis/TypeChecker.cpp(531)`

## Displayed message
`Throw in function void dev::solidity::TypeChecker::checkDoubleStorageAssignment(const dev::solidity::Assignment&)`

## Example code
```solidity
pragma solidity ^0.4.24;
contract CrashContract {
       struct S { }
       S x;
       function f() public {
               (x, x) = 1(x, x);
       }
}
```


#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2018-08-06 23:12](https://github.com/ethereum/solidity/issues/4711#issuecomment-410881440):

Reproducible in 0.4.24 and still happens in develop:
```
Internal compiler error during compilation:
/Users/alex/Projects/solidity/libsolidity/analysis/TypeChecker.cpp(510): Throw in function void dev::solidity::TypeChecker::checkDoubleStorageAssignment(const dev::solidity::Assignment &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::solidity::InternalCompilerError>
std::exception::what: 
[dev::tag_comment*] = 
```


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
