# [\#9592 Issue](https://github.com/ethereum/solidity/issues/9592) `closed`: `try`/`catch` for low-level external calls
**Labels**: `documentation :book:`, `low effort`, `low impact`, `should have`, `closed due inactivity`, `stale`


#### <img src="https://avatars.githubusercontent.com/u/381065?u=585f25e91bab7dc4974e01070d91a13cbfeab251&v=4" width="50">[adridadou](https://github.com/adridadou) opened issue at [2020-08-07 13:52](https://github.com/ethereum/solidity/issues/9592):

<!--## Prerequisites

- First, many thanks for taking part in the community. We really appreciate that.
- We realize there is a lot of information requested here. We ask only that you do your best to provide as much information as possible so we can better help you.
- Support questions are better asked in one of the following locations:
	- [Solidity chat](https://gitter.im/ethereum/solidity)
	- [Stack Overflow](https://ethereum.stackexchange.com/)
- Ensure the issue isn't already reported.
- The issue should be reproducible with the latest solidity version; however, this isn't a hard requirement and being reproducible with an older version is sufficient.
-->

## Description

<!--Please shortly describe the bug you have found, and what you expect instead.-->
I'm trying to use the new try / catch feature but it seems that it doesn't recognise address.call to be an external call

## Environment

- Compiler version: 0.7.0
- Target EVM version (as per compiler settings): default
- Framework/IDE (e.g. Truffle or Remix): Truffle and Remix
- EVM execution environment / backend / blockchain client: it's a compilation issue so not relevant
- Operating system: OSX

## Steps to Reproduce

try to compile : 
```
pragma solidity ^0.7.0;


contract TryCatchIssue {
    address payable externalAddress;
    constructor(address payable addr) {
        externalAddress = addr;
    }
    
    
    function callme(bytes calldata data) external {
        try externalAddress.call{value: 100}(data) {
            
        } catch (string memory reason) {
            revert(reason);
        } catch (bytes memory reason) {
            revert();
        }
    }
}
```

I'm expecting to use try / catch but instead I get the error message:
`Try can only be used with external function calls and contract creation calls.`

<!--
Please provide a *minimal* source code example to trigger the bug you have found.
Please also mention any command line flags that are necessary for triggering the bug.
Provide as much information as necessary to reproduce the bug.

```solidity
// Some *minimal* Solidity source code to reproduce the bug.
// ...
```
-->


#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2020-08-10 13:46](https://github.com/ethereum/solidity/issues/9592#issuecomment-671363663):

I don't remember what was the main requirement, but either we should support `.call`/`.delegatecall`/`.staticall` or report a better error.

#### <img src="https://avatars.githubusercontent.com/u/381065?u=585f25e91bab7dc4974e01070d91a13cbfeab251&v=4" width="50">[adridadou](https://github.com/adridadou) commented at [2020-08-10 13:50](https://github.com/ethereum/solidity/issues/9592#issuecomment-671365858):

yes exactly. I'm trying to retrieve the reason for an error and I have no way if you use .call (or similar calls)

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2020-08-10 14:04](https://github.com/ethereum/solidity/issues/9592#issuecomment-671374867):

Low-level calls return a tuple ``(bool, bytes memory)`` - the ``bool`` indicating, if the call failed, the ``bytes memory`` containing the error message as an ABI-encoded call to a function with signature ``Error(string)``. So with low-level calls you are supposed to manually decode the message.
The ``bytes memory`` part will consist of the 4-byte signature of ``Error(string)`` followed by a pointer to the string, which in turn consists of a length and the padded string data.
So for ``revert("abc");`` you can expect the ``bytes memory`` to contain the following:
```
0x08c379a0 -- first 4 bytes of the keccak256 hash of "Error(String)"
0x0000000000000000000000000000000000000000000000000000000000000020 -- relative offset of the string argument
0x0000000000000000000000000000000000000000000000000000000000000003 -- length of the string
0x6162630000000000000000000000000000000000000000000000000000000000 -- padded string "abc"
```

Possibly, we will have a ``try...catch``-like mechanism for low-level calls in the future - or will at least make it easier to decode the error message using ``abi.decode`` with memory array slices. But currently decoding this will involve some manual effort.

#### <img src="https://avatars.githubusercontent.com/u/381065?u=585f25e91bab7dc4974e01070d91a13cbfeab251&v=4" width="50">[adridadou](https://github.com/adridadou) commented at [2020-08-10 14:51](https://github.com/ethereum/solidity/issues/9592#issuecomment-671402708):

ooh that's great news ! Ok I will be using that then.
I would add this to the documentation. In the documentation there is nothing related to the error case and what is returned.

Looking at the return value, it would be nice if there was a way in solidity to handle that without splitting the bytes array

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) commented at [2020-08-10 17:45](https://github.com/ethereum/solidity/issues/9592#issuecomment-671494995):

We'll keep this open for looking into improving the documentation about this.
And hopefully in the future we'll have some mechanisms that makes this easier than having to deal with the raw bytes data.

#### <img src="https://avatars.githubusercontent.com/u/381065?u=585f25e91bab7dc4974e01070d91a13cbfeab251&v=4" width="50">[adridadou](https://github.com/adridadou) commented at [2020-08-11 14:49](https://github.com/ethereum/solidity/issues/9592#issuecomment-671992775):

for anyone getting here and looking for a solution, here is an example on how to do it:
https://ethereum.stackexchange.com/questions/83528/how-can-i-get-the-revert-reason-of-a-call-in-solidity-so-that-i-can-use-it-in-th

#### <img src="https://avatars.githubusercontent.com/u/702124?u=00e20e1963ccc9a908a5826b2d8c3b1b1f6acea4&v=4" width="50">[k06a](https://github.com/k06a) commented at [2022-11-29 15:46](https://github.com/ethereum/solidity/issues/9592#issuecomment-1330852083):

Good idea!

#### <img src="https://avatars.githubusercontent.com/in/15368?v=4" width="50">[github-actions](https://github.com/apps/github-actions) commented at [2023-05-14 12:03](https://github.com/ethereum/solidity/issues/9592#issuecomment-1546883877):

This issue has been marked as stale due to inactivity for the last 90 days.
It will be automatically closed in 7 days.

#### <img src="https://avatars.githubusercontent.com/u/702124?u=00e20e1963ccc9a908a5826b2d8c3b1b1f6acea4&v=4" width="50">[k06a](https://github.com/k06a) commented at [2023-05-15 07:50](https://github.com/ethereum/solidity/issues/9592#issuecomment-1547358590):

I believe this is still worth implementing

#### <img src="https://avatars.githubusercontent.com/in/15368?v=4" width="50">[github-actions](https://github.com/apps/github-actions) commented at [2023-08-13 12:03](https://github.com/ethereum/solidity/issues/9592#issuecomment-1676338563):

This issue has been marked as stale due to inactivity for the last 90 days.
It will be automatically closed in 7 days.

#### <img src="https://avatars.githubusercontent.com/in/15368?v=4" width="50">[github-actions](https://github.com/apps/github-actions) commented at [2023-08-21 12:04](https://github.com/ethereum/solidity/issues/9592#issuecomment-1686202650):

Hi everyone! This issue has been automatically closed due to inactivity.
If you think this issue is still relevant in the latest Solidity version and you have something to [contribute](https://docs.soliditylang.org/en/latest/contributing.html), feel free to reopen.
However, unless the issue is a concrete proposal that can be implemented, we recommend starting a language discussion on the [forum](https://forum.soliditylang.org) instead.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
