# [\#10977 PR](https://github.com/ethereum/solidity/pull/10977) `merged`: Replace raw throw with BOOST_THROW_EXCEPTION.

#### <img src="https://avatars.githubusercontent.com/u/5008794?u=aa5f725afdad81154a79cd5ab6be9340b08da4a9&v=4" width="50">[aarlt](https://github.com/aarlt) opened issue at [2021-02-19 01:25](https://github.com/ethereum/solidity/pull/10977):



#### <img src="https://avatars.githubusercontent.com/u/13174375?u=52d702cb6bec53b561afa293cf9cd53ef7a63924&v=4" width="50">[hrkrshnn](https://github.com/hrkrshnn) commented at [2021-02-19 12:42](https://github.com/ethereum/solidity/pull/10977#issuecomment-782051456):

Why is this done?

#### <img src="https://avatars.githubusercontent.com/u/137030?v=4" width="50">[cameel](https://github.com/cameel) commented at [2021-02-19 12:45](https://github.com/ethereum/solidity/pull/10977#issuecomment-782052734):

I'm not sure about the original motivation but it looks like a good change because `BOOST_THROW_EXCEPTION()` includes the information about file name and line number so we have more info when things go wrong.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
