# [\#15605 Issue](https://github.com/ethereum/solidity/issues/15605) `open`: SMTChecker: Cross-contract function calls cause the BMC model to crash.
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/147013944?v=4" width="50">[Subway2023](https://github.com/Subway2023) opened issue at [2024-12-02 14:12](https://github.com/ethereum/solidity/issues/15605):

## Environment

- Compiler version: 0.8.28
- Target EVM version (as per compiler settings): Non
- Framework/IDE (e.g. Truffle or Remix): None
- EVM execution environment / backend / blockchain client: None
- Operating system: Ubuntu

## Steps to Reproduce

```solidity
contract Combined {
    C1 internal c1;
    constructor() {
        c1 = new C1();
    }
    function invokeAndCheck() public {
        c1.set();
        assert(c1.n() <= 1);
    }
}
contract C1 {
    uint public n;
    function set() external {
        n = 1;
    }
}
```
```
solc-0828 b.sol --model-checker-ext-calls trusted --model-checker-timeout 0 --model-checker-engine bmc --model-checker-bmc-loop-iterations 10 --model-checker-solvers z3
```
```
Internal compiler error:
./libsolidity/formal/SMTEncoder.cpp(2513): Throw in function solidity::smtutil::Expression solidity::frontend::SMTEncoder::currentValue(const solidity::frontend::VariableDeclaration&) const
Dynamic exception type: boost::wrapexcept<solidity::langutil::InternalCompilerError>
std::exception::what: Solidity assertion failed
[solidity::util::tag_comment*] = Solidity assertion failed
```
If I comment out assert(c1.n() <= 1), the BMC model can be called normally. Even without commenting it out, the CHC model can be called normally.











-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2024.12.15 at 06:45:24.]
