# [\#561 Issue](https://github.com/ethereum/solidity/issues/561) `closed`: The `using` keyword causes `unknown exception` if the recipient method is not found
**Labels**: `bug :bug:`


#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) opened issue at [2016-05-12 17:30](https://github.com/ethereum/solidity/issues/561):

This code causes `Unknown exception during compilation.`:

```
library B {
    function b() {
    }
}

contract A {
    using B for bytes;

    function a() {
        bytes memory x;
        x.b();
    }
}
```

Adding the proper parameter type (i.e. `function b(bytes a) {`) to `B.b()` fixes it.


#### <img src="https://avatars.githubusercontent.com/u/20340?v=4" width="50">[axic](https://github.com/axic) commented at [2016-05-12 17:30](https://github.com/ethereum/solidity/issues/561#issuecomment-251935932):

The crash was fixed in #1033, but we should have a proper check and error message in the TypeChecker.


-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
