# [\#4270 Issue](https://github.com/ethereum/solidity/issues/4270) `closed`: Exception handling in soltest.

#### <img src="https://avatars.githubusercontent.com/u/1347491?v=4" width="50">[ekpyron](https://github.com/ekpyron) opened issue at [2018-06-11 21:17](https://github.com/ethereum/solidity/issues/4270):

Came up in #4064.

In case of failing assertions (``solAssert``) in extracted syntax tests, ``soltest`` does not properly handle and report the exceptions, resulting in errors like:

```
failure

ASSERTION FAILURE:
- file   : SyntaxTest.cpp
- line   : 274
- message: unexpected exception thrown by { stringstream errorStream; if (!SyntaxTest(fullpath.string()).run(errorStream)) do { ::boost::unit_test::unit_test_log.set_checkpoint( ::boost::unit_test::const_string( "/root/project/test/libsolidity/SyntaxTest.cpp", sizeof( "/root/project/test/libsolidity/SyntaxTest.cpp" ) - 1 ), static_cast<std::size_t>(274) ); ::boost::test_tools::tt_detail:: report_assertion ( (false), (::boost::unit_test::lazy_ostream::instance() << "Test expectation mismatch.\n" + errorStream.str()), ::boost::unit_test::const_string( "/root/project/test/libsolidity/SyntaxTest.cpp", sizeof( "/root/project/test/libsolidity/SyntaxTest.cpp" ) - 1 ), static_cast<std::size_t>(274), ::boost::test_tools::tt_detail::CHECK, ::boost::test_tools::tt_detail::CHECK_MSG , 0 ); } while( ::boost::test_tools::tt_detail::dummy_cond() ); }
```

Whereas ``isoltest`` properly reports the exception/assertion:
```
syntaxTests/nameAndTypeResolution/312_leading_zero_rationals_convert.sol: InternalCompilerError: Number of fractional digits do not fit the specified bit width
```





-------------------------------------------------------------------------------



[Export of Github issue for [ethereum/solidity](https://github.com/ethereum/solidity). Generated on 2022.05.23 at 03:51:38.]
